[[redirects]]
from = "/*"
to = "functions/sycamore-netlify-functions"
status = 200

[build]
command = "make build"
publish = "public"
functions = "functions"

[dev]
command = "make build"
publish = "public"
functions = "functions"
port = 8000
targetPort = 8080
framework = "#custom"
